/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem { 'text' : string, 'isComplete' : boolean }
export interface Goal {
  'isCompleted' : boolean,
  'text' : string,
  'targetDate' : Time,
}
export interface PerformanceRating { 'date' : Time, 'score' : bigint }
export interface Reflection { 'content' : string, 'date' : string }
export interface Task {
  'status' : boolean,
  'title' : string,
  'dueDate' : Time,
  'description' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addDaily' : ActorMethod<[string], undefined>,
  'addGoal' : ActorMethod<[string, Time], undefined>,
  'addTask' : ActorMethod<[string, string, Time], undefined>,
  'getAllPerformanceRatings' : ActorMethod<[], Array<PerformanceRating>>,
  'getAllReflections' : ActorMethod<[], Array<Reflection>>,
  'getDailies' : ActorMethod<[], Array<ChecklistItem>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getPerformanceRating' : ActorMethod<[Time], [] | [PerformanceRating]>,
  'getReflection' : ActorMethod<[string], [] | [Reflection]>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'saveReflection' : ActorMethod<[string, string], undefined>,
  'setPerformanceRating' : ActorMethod<[Time, bigint], undefined>,
  'toggleDaily' : ActorMethod<[string], undefined>,
  'toggleTaskStatus' : ActorMethod<[string], undefined>,
  'updateGoalStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];