/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PerformanceRating = IDL.Record({
  'date' : Time,
  'score' : IDL.Nat,
});
export const Reflection = IDL.Record({
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const ChecklistItem = IDL.Record({
  'text' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const Goal = IDL.Record({
  'isCompleted' : IDL.Bool,
  'text' : IDL.Text,
  'targetDate' : Time,
});
export const Task = IDL.Record({
  'status' : IDL.Bool,
  'title' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDaily' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func([IDL.Text, Time], [], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'getAllPerformanceRatings' : IDL.Func(
      [],
      [IDL.Vec(PerformanceRating)],
      ['query'],
    ),
  'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getDailies' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getPerformanceRating' : IDL.Func(
      [Time],
      [IDL.Opt(PerformanceRating)],
      ['query'],
    ),
  'getReflection' : IDL.Func([IDL.Text], [IDL.Opt(Reflection)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'saveReflection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setPerformanceRating' : IDL.Func([Time, IDL.Nat], [], []),
  'toggleDaily' : IDL.Func([IDL.Text], [], []),
  'toggleTaskStatus' : IDL.Func([IDL.Text], [], []),
  'updateGoalStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PerformanceRating = IDL.Record({ 'date' : Time, 'score' : IDL.Nat });
  const Reflection = IDL.Record({ 'content' : IDL.Text, 'date' : IDL.Text });
  const ChecklistItem = IDL.Record({
    'text' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const Goal = IDL.Record({
    'isCompleted' : IDL.Bool,
    'text' : IDL.Text,
    'targetDate' : Time,
  });
  const Task = IDL.Record({
    'status' : IDL.Bool,
    'title' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addDaily' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func([IDL.Text, Time], [], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'getAllPerformanceRatings' : IDL.Func(
        [],
        [IDL.Vec(PerformanceRating)],
        ['query'],
      ),
    'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getDailies' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getPerformanceRating' : IDL.Func(
        [Time],
        [IDL.Opt(PerformanceRating)],
        ['query'],
      ),
    'getReflection' : IDL.Func([IDL.Text], [IDL.Opt(Reflection)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'saveReflection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setPerformanceRating' : IDL.Func([Time, IDL.Nat], [], []),
    'toggleDaily' : IDL.Func([IDL.Text], [], []),
    'toggleTaskStatus' : IDL.Func([IDL.Text], [], []),
    'updateGoalStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };